name: Build G2

on:
  push:
    branches:
      - edge
      - edge-preview
      - dev-*
  # pull_request:
  #   branches:

jobs:
  Build:
    name: Checkout and Build
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v3
      with:
        path: ./Motate/Tools/linux
        key: ${{ runner.os }}-tools-03 # Change the number to invalidate the tools caches

    - name: prepare
      working-directory: ${{ github.workspace }}/g2core/
      run: |
        mkdir -p ./bin/ARTIFACTS/

    - name: make CONFIG=Othermill
      working-directory: ${{ github.workspace }}/g2core/
      run: |
        make CONFIG=Othermill VERBOSE=2 COLOR=0
        cp ./bin/Othermill-g2v9k/g2core-summed.bin ./bin/ARTIFACTS/g2core-Othermill-g2v9k-`git describe --abbrev=4 --dirty --always --tags`.bin

    - name: make CONFIG=OthermillPro
      working-directory: ${{ github.workspace }}/g2core/
      run: |
        make CONFIG=OthermillPro VERBOSE=2 COLOR=0
        cp ./bin/OthermillPro-g2v9k/g2core-summed.bin ./bin/ARTIFACTS/g2core-OthermillPro-g2v9k-`git describe --abbrev=4 --dirty --always --tags`.bin

    - name: Archive binaries
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: ./g2core/bin/ARTIFACTS
